# build.yaml
# ...

targets:
  $default:
    builders:
      flutter_gen_runner: # or flutter_gen
        options:
          output: lib/gen/ # Optional (default: lib/gen/)
          line_length: 120 # Optional (default: 80)
